[versions]
# Plugin Version
kotlin = "1.9.10"
androidGradlePlugin = "8.2.0"
minSDK = "24"
targetSDK = "34"
versionCode = "1"
versionName = "1.0.0"
buildTools = "34.0.0"

# AndroidX
core-ktx = "1.12.0"
appcompat = "1.6.1"
material = "1.10.0"
constraintlayout = "2.1.4"
activity = "1.8.1"
fragment = "1.6.2"
navigation = "2.7.5"
datastore = "1.0.0"
room = "2.6.1"
paging = "3.2.1"

# Firebase
gms = "4.4.0"
firebase-bom = "32.6.0"

# Timber
timber = "5.0.1"

# Kotlinx
coroutine = "1.7.1"
datetime = "0.4.0"

#Test
junit = "4.13.2"
junit-ext = "1.1.5"
core-espresso = "3.5.1"

# Version Catalog Auto Update
banManes = "0.41.0"
little-robots = "0.8.0"

#Libraries
retrofit = "2.9.0"
moshi-converter = "2.9.0"
httplogginginterceptor = "4.11.0"
circleimageview = "3.1.0"
glide = "4.15.1"

# Authentication
auth0 = "2.9.1"

#hilt
hilt = "2.48.1"

#lottie
lottie = "6.1.0"

#WYSIWYG
richeditor = "2.0.0"

#Kakao Map
kakaomap = "2.6.0"

[plugins]
# Project Dependency
android-application = { id = "com.android.application", version.ref = "androidGradlePlugin" }
android-library = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin-plugin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
banManes = { id = "com.github.ben-manes.versions", version.ref = "banManes" }
littleRobots = { id = "nl.littlerobots.version-catalog-update", version.ref = "little-robots" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt" }
gms = { id = "com.google.gms.google-services", version.ref = "gms" }
safeargs = { id = "androidx.navigation.safeargs", version.ref = "navigation"}

[libraries]
# AndroidX
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "core-ktx" }
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
constraintlayout = { group = "androidx.constraintlayout", name = "constraintlayout", version.ref = "constraintlayout" }
test-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junit-ext" }
espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "core-espresso" }
littleRobots = { group = "nl.littlerobots.vcu", name = "plugin", version.ref = "little-robots" }
activity = { group = "androidx.activity", name = "activity", version.ref = "activity" }

activity-ktx = { group = "androidx.activity", name = "activity-ktx", version.ref = "activity" }
fragment-ktx = { group = "androidx.fragment", name = "fragment-ktx", version.ref = "fragment" }
navigation = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigation" }
navigation-ui = { group = "androidx.navigation", name = "navigation-ui-ktx", version.ref = "navigation" }

room-ktx = { group = "androidx.room", name = "room-ktx", version.ref = "room" }
room-compiler = { group = "androidx.room", name = "room-compiler", version.ref = "room"}

paging = { group = "androidx.paging", name = "paging-runtime", version.ref = "paging"}

datastore-preference = { group = "androidx.datastore", name = "datastore-preferences", version.ref = "datastore" }

# Google
material = { group = "com.google.android.material", name = "material", version.ref = "material" }

# Coroutine
coroutine = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-android", version.ref = "coroutine" }
datetime = { group = "org.jetbrains.kotlinx", name = "kotlinx-datetime", version.ref = "datetime"}

# Firebase
firebase-bom = { group = "com.google.firebase", name = "firebase-bom", version.ref = "firebase-bom" }
firebase-analytics = { group = "com.google.firebase", name = "firebase-analytics-ktx" }

# Test
junit = { group = "junit", name = "junit", version.ref = "junit" }

#coroutine

#lottie
lottie = { group = "com.airbnb.android", name = "lottie", version.ref = "lottie" }

#retrofit , moshi
retrofit = { group = "com.squareup.retrofit2", name = "retrofit", version.ref = "retrofit" }
moshi = { group = "com.squareup.retrofit2", name = "converter-moshi", version.ref = "moshi-converter" }
logging-interceptor = { group = "com.squareup.okhttp3", name = "logging-interceptor", version.ref = "httplogginginterceptor" }

#viewmodel

#Logger
timber = { group = "com.jakewharton.timber", name = "timber", version.ref = "timber" }

#Hilt
hilt-android = { group = "com.google.dagger", name = "hilt-android", version.ref = "hilt" }
hilt-compiler = { group = "com.google.dagger", name = "hilt-compiler", version.ref = "hilt" }

# Authentication
auth0 = { group = "com.auth0.android", name = "auth0", version.ref = "auth0" }

# Dependencies included in Build-logic
android-gradlePlugin = { group = "com.android.tools.build", name = "gradle", version.ref = "androidGradlePlugin" }
kotlin-gradlePlugin = { group = "org.jetbrains.kotlin", name = "kotlin-gradle-plugin", version.ref = "kotlin" }

# circleimageview
circleimageview = { group = "de.hdodenhof", name = "circleimageview", version.ref = "circleimageview" }

glide = { group = "com.github.bumptech.glide", name = "glide", version.ref = "glide" }

# WYSIWYG
richeditor = { group = "jp.wasabeef", name = "richeditor-android", version.ref = "richeditor" }

# Kakao Map
kakaomap = { group = "com.kakao.maps.open", name = "android", version.ref = "kakaomap" }
[bundles]

